### ISSUE TITLE
KNN plot script

### ISSUE THREAD

**Issue by AdaChou1** [BernsteinLab/aml2019#1]
Hi, the artical is really a impressive job! I'm really interested in how you used KNN to cluster the normal cells into nicely ordered groups. Actually I'm trying to classify my data in the same way but I can't give it a proper order to arrange them with development trajactory. Hope you can upload the scripts soon~:-)

**Comment by hovestadt** [comment]
Thank you for your comment. We used KNN graphs for visualization (using SPRING), and BackSPIN for clustering. `03 Unsupervised clustering/1_prepareBackSpinKNN.R` contains the code that was used to generate the input files required for these tools. Please let me know if you have any other comment.
