### ISSUE TITLE
Questions about the scripts

### ISSUE THREAD

**Issue by Zifeng-L** [BernsteinLab/aml2019#3]
Hi, here. 
Thanks for your great work on AML. I want to use these methods for my own data, so I downloaded the dem matrix from your GEO database and tried to repeat your analysis. When I load the healthy BM data and run the scripts named "prepareBackSpinKNN" and "RFtrained", I found the number of cells after filtering would not match the cells you provided in "BM_6952cells.BackSPIN.txt".

I used the code as followed
```
D.umi <- colSums(D)  # calculate once and use for all filtering steps
# only keep genes mapping to a single chromosome (excluding X and Y)
D <- filterGenes(D, none.filter, D.umi, main="none")
D <- filterGenes(D, multi.filter, D.umi, main="multi")
D <- filterGenes(D, xy.filter, D.umi, main="xy")  # use this when comparing samples from both M and F
# exclude cells with high mitochondrial or rRNA transcripts
D <- filterGenes(D, mt, D.umi, 0.2, main="mitochondrial genes")  # cells with >20% mitochondrial RNAs are filtered. change QC thresholds here
D <- filterGenes(D, rr, D.umi, 0.2, main="ribosomal rnas")  # cells with >20% ribosomal RNAs are filtered
D <- filterGenes(D, rp, D.umi, main="ribosomal proteins")  
```
Then I got 7698 cells for analysis, but your text provided 6915 cells. So I wondered if there were something wrong with the process of filtering?  I check the overlap between the two datasets was 4677 cells.
Can you check that data and help me? Thanks a lot!

**Comment by hovestadt** [comment]
Please see in the methods:
BackSPIN clustering: Initial QC yielded 7,698 cells from normal BM donors. We randomly filtered 783 cells of 1,590 BM5 CD34+CD38– cells to reduce representation of this population. The remaining 6,915 normal BM cells were then clustered into cell types using BackSPIN.

Just checked that all cells are on GEO with the same cell IDs. Could you try again?

**Comment by Zifeng-L** [comment]
> Please see in the methods:
> BackSPIN clustering: Initial QC yielded 7,698 cells from normal BM donors. We randomly filtered 783 cells of 1,590 BM5 CD34+CD38– cells to reduce representation of this population. The remaining 6,915 normal BM cells were then clustered into cell types using BackSPIN.
> 
> Just checked that all cells are on GEO with the same cell IDs. Could you try again?

I tried again, but the overlap between initial QC yielded (7,698 cells) and your text (BM_6952cells.BackSPIN.txt) was still 4677 cells. Maybe there was something wrong with the cell IDs. Could you check the BM_6952cells.BackSPIN.txt?

**Comment by hovestadt** [comment]
I checked and all the cells are all there. Please check which cells are missing in your analysis and look for them manually.

**Comment by Zifeng-L** [comment]
> I checked and all the cells are all there. Please check which cells are missing in your analysis and look for them manually.

I found the mistake. When I loaded the dataset, the cell IDs containing the dash were converted into a period. Thanks for your help! 
There was still one thing that puzzled me. I read the scripts and use the dem matrix as d, I wonder what does the "d.stats" contains?

**Comment by hovestadt** [comment]
Glad you figured it out. d.stats probably contains the information that's in the "anno.txt" files on GEO. not sure it's needed for the script.

**Comment by Zifeng-L** [comment]
> Glad you figured it out. d.stats probably contains the information that's in the "anno.txt" files on GEO. not sure it's needed for the script.

Many thanks for your help!

**Comment by Zifeng-L** [comment]
> Glad you figured it out. d.stats probably contains the information that's in the "anno.txt" files on GEO. not sure it's needed for the script.

Sorry to bother you again! I wonder to know that how can I get "AMLmut_923cells.RData" from GEO? I checked the data but could not found it. Thanks!
