### ISSUE TITLE
Question about out-of-bag error

### ISSUE THREAD

**Issue by Zifeng-L** [BernsteinLab/aml2019#4]
Hi, here! I have some doubts about the out-of-bag error in your paper methods.
"We used Random forest-based classification for two different purposes: To predict similarity of single cells to the 15 different cell types detected in healthy BM (classifier 1), and to predict if a single cell from a tumor sample is malignant or normal (classifier 2). To train the first classifier, we first performed a feature selection step to select the most informative genes from all 14,554 expressed genes in the dataset (average expression > 0.01). Feature selection was performed by training an “outer” random forest classifier on all expressed genes. We trained 1,000 trees, using a random subset of 50 cells from each cell type for each tree. Based on the reported overall gene importance in the “outer” classifier, we then selected only the 1,000 most informative genes for the training of the “inner” classifier. The reported out-of-bag (OOB) error (i.e. misclassification error of cells that were not used for learning of a given tree) was 20% lower for the “inner” than for the “outer” classifier, justifying the use of an initial feature selection step."
As you said in the paper, the OOB error was 20% lower for the "inner" than for the "outer" classifier. However, I repeated the analysis following your scripts using the processed data on GEO, the results seemed to be inconsistent with yours.

![image](https://user-images.githubusercontent.com/53402047/126637476-bc3c7edb-6beb-4775-8821-ffe787008cad.png)
![image](https://user-images.githubusercontent.com/53402047/126637513-8eba84a8-0686-406a-a4a8-905498b0d2a3.png)

The difference between the "inner" and "outer" classifier is 2%. Could you help me?

**Comment by hovestadt** [comment]
14.46/12.19 ≈ 80%, i.e. 20% lower.
