### ISSUE TITLE
Question about "AMLmut_923cells.RData"

### ISSUE THREAD

**Issue by Zifeng-L** [BernsteinLab/aml2019#5]
Hi, here.
Thanks for your great work on AML. I want to use these methods for my own data, so I downloaded the dem matrix from your GEO database and tried to repeat your analysis. I wonder to know that how can I get "AMLmut_923cells.RData" from GEO? I checked the data but could not found it. Thanks!

**Comment by modalaigh** [comment]
Hi @Zifeng-L, did you manage to find out which cells are in the "AMLmut_923cells.RData" file? I currently have the same issue that you did. I downloaded the 35 anno.txt files from GEO for the AML patients and saw that there was a column labelled "MutTranscripts". I initially thought that the cells with entries in this column would represent those cells belonging to "AMLmut_923cells.RData" but when I counted all the cells with entries, I ended up with 939 cells which is a bit more than what I was expecting.

**Comment by petervangalen** [comment]
If you want to use the mutation data, I suggest loading the .anno.txt files. The `MutTranscripts` and `WtTranscripts` columns contain the mutation calls and the number of supporting reads (separated by /)

**Comment by yi6kim** [comment]
I had the same observation, @modalaigh . 
When I constructed the dataset myself using the 35 anno.txt files from GEO (as the .RData itself is not given), I ended up with 939 cells not 923 cells.

**Comment by Yousuk-Song** [comment]
@yi6kim @modalaigh

Hi, I'm working on the same process, and I'm struggling to build AMLmut_923cells.RData too. Could you tell me how did you ended up with 939? 

I see this information on a*nnot.txt.gz
MutTranscripts  WtTranscripts
normal  malignant 
normal  malignant 
normal  malignant 
malignant  normal  

and counting cell_ids in which MutTranscripts==malignant can't make results even close to 900s

I really appreciate for your reply

**Comment by yi6kim** [comment]
@Yousuk-Song  Are you sure you added up all 35 annotation files? 

When I iterate through the files:

AML.anno.filenames <- list.files("my_directory",  full.names = TRUE, pattern = "AML.*\\.anno\\.txt$")[1:35]
mut_counts <- c()
for (i in 1:35){
mut_counts[i]= sum(table(read.delim(AML.anno.filenames[i], header = T, na.strings = "")$MutTranscripts))
}
print(mut_counts)
> 15  45   0   0   3   1   3  27  92   0   0   6   0 146   6   0   0   6   1 367   8   2  37   0   3   0   0   1   0   0   0  21 143   6   0

print(sum(mut_counts))
>939

**Comment by Yousuk-Song** [comment]
Thank You so much! I followed your method, chose cells without "MutTranscripts == normal" and got the same results, 939. 

I don't understand why are there no explanation or any mentions about the number '923' in the article.

**Comment by petervangalen** [comment]
I confirm there are 939 mutated cells across all AML samples.

**Comment by folklore-evermore** [comment]
@Zifeng-L Have you got the RData finally?
